backend:
  name: github
  # change repo to your git repository url
  branch: master
  repo: fahadsaleem164/arz
media_folder: static/assets
public_folder: /assets

collections:
  - name: Main Section
    label: Main Section
    label_singular: Main Section
    folder: src/pages/posts/mainSection/
    summary: '{{title}}'
    delete: false
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Home page.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'description', name: 'text', widget: 'text' }
      - { label: 'Link', name: 'link', widget: 'string' }
      
       
  - name: ourServices
    label: What We Do
    label_singular:  Services
    folder: src/pages/posts/ourServices/
    slug: "{{title}}"
    summary: '{{title}}'
    delete: false 
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Services.
    fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'text' }
        - { label: 'Link', name: 'link', widget: 'string'}
        - label: 'Our Services'
          name: 'ourservices'
          widget: 'list'
          fields:
             - { label: 'Title', name: 'title', widget: 'string' }
             - { label: 'Description', name: 'description', widget: 'text' }
             - { label: 'Link', name: 'link', widget: 'string' }
             - { label: 'Image', name: 'image', widget: 'image' }
        


  - name: WhyChooseUs
    label: Why Choose Us
    label_singular:  Why Choose Us
    folder: src/pages/posts/whyUseUs/
    slug: "{{title}}"
    summary: '{{title}}'
    delete: false 
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for HOME PAGE.
    fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'text' }
        - { label: 'Video', name: 'video', widget: 'file'}
        - { label: 'Projects Done', name: 'projects_done', widget: 'string'}
        - { label: 'Conversion Rate', name: 'conservation_rate', widget: 'string'}
        - { label: 'Returning Happy Customer', name: 'return_happy_customer', widget: 'string'}
       

  - name: WhoWeAre
    label: Who We Are
    label_singular:  WHO We are
    folder: src/pages/posts/whoWeAre/
    slug: "{{title}}"
    summary: '{{title}}'
    delete: false 
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for HOME PAGE.
    fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'text' }
        - { label: 'image 1', name: 'image1', widget: 'image'}
        - { label: 'image 2', name: 'image2', widget: 'image' }
  

  - name: OurMission
    label: Our Mission
    label_singular:  Our Mission
    folder: src/pages/posts/ourMission/
    slug: "{{title}}"
    summary: '{{title}}'
    delete: false 
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for HOME PAGE.
    fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'text' }
        - { label: 'image 1', name: 'image1', widget: 'image'}
        - { label: 'image 2', name: 'image2', widget: 'image' }
        - { label: 'Link', name: 'link', widget: 'string', hint: 'Link for Get Started' }


  - name: CaseStudies
    label: Case Studies
    label_singular:  Case Studies
    folder: src/pages/posts/caseStudy/
    slug: "{{title}}"
    summary: '{{title}}'
    delete: false 
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for HOME PAGE.
    fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - label: 'Case Studies'
          name: 'Case Studies'
          widget: 'list'
          maximum: 3
          minimum: 1
          fields:
             - { label: 'Image', name: 'image', widget: 'image' }
             - { label: 'Title', name: 'title', widget: 'string', hint: 'Link for Get Started' }
             - { label: 'Description', name: 'description', widget: 'text', hint: 'Link for Get Started' }
             - { label: 'Link', name: 'link', widget: 'string', hint: 'Link for Get Started' }
      


  


 
        
  