backend:
  name: github
  # change repo to your git repository url
  branch: main
  repo: fahadsaleem164/arz
media_folder: static/assets
public_folder: /assets

collections:
  - name: homepage
    label: Home Page
    label_singular: Home Page
    folder: src/pages/posts/homeage/
    summary: '{{title}}'
    create: true
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for Home page.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'description', name: 'text', widget: 'markdown', hint: 'Description will be here' }
      - { label: 'Link', name: 'link', widget: 'string', hint: 'Link for Get Started' }
      - { label: 'image', name: 'image', widget: 'image', hint: 'Link for Get Started' }
      - label: 'Our Services'
        name: 'ourservices'
        widget: 'object'
        fields:
             - { label: 'Title', name: 'title', widget: 'string' }
             - { label: 'Link', name: 'link', widget: 'string', hint: 'Link for Get Started' }
             - { label: 'Description', name: 'description', widget: 'text', hint: 'Link for Get Started' }
             - label: 'Our Services'
               name: 'ourservices'
               widget: 'list'
               fields:
                    - { label: 'Title', name: 'title', widget: 'string' }
                    - { label: 'Description', name: 'description', widget: 'text', hint: 'Description will be here' }
                    - { label: 'image', name: 'image', widget: 'image', hint: 'Link for Get Started' }
      - label: 'Why Choose Us'
        name: 'Whychooseus'
        widget: 'object'
        fields:
             - { label: 'Title', name: 'title', widget: 'string' }
             - { label: 'Description', name: 'description', widget: 'text', hint: 'Link for Get Started' }
             - { label: 'Video', name: 'video', widget: 'file', hint: 'Upload your vedeo' }


  - name: Who We Are
    label: whoweare
    label_singular:  WHO We are
    folder: src/pages/posts/homepage/
    slug: "{{title}}"
    summary: '{{title}}'
    delete: false 
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for HOME PAGE.
    fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'text' }
        - { label: 'image 1', name: 'image1', widget: 'image'}
        - { label: 'image 2', name: 'image2', widget: 'image' }
  

  - name: Our Mission
    label: ourmission
    label_singular:  Our Mission
    folder: src/pages/posts/homepage/
    slug: "{{title}}"
    summary: '{{title}}'
    delete: false 
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for HOME PAGE.
    fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'text' }
        - { label: 'image 1', name: 'image1', widget: 'image'}
        - { label: 'image 2', name: 'image2', widget: 'image' }
        - { label: 'Link', name: 'link', widget: 'string', hint: 'Link for Get Started' }


 
        
  